#!/bin/sh

case $1 in
    start)
        echo
        echo -n "(librespot)"
        echo

        librespot   --username xxx@xxx.xxx \
                    --password xxxxxxxxxxx \
                    --backend "jackaudio" -b 320 \
                    --initial-volume 100 \
                    --format F32 \
                    --name pre.di.c \
            > /dev/null
    ;;
    stop)
        killall librespot
    ;;
    *)
        echo
        echo "usage: librespot <start|stop>"
        echo
    ;;
esac

exit
