#!/bin/sh

case $1 in
    start)
        echo
        echo -n "(librespot)"
        echo

        librespot   --username "filarete@gmail.com" \
                    --password "-_bX:4XcijL~:-m" \
                    --backend jackaudio -b 320 \
                    # bypass volume
                        --mixer softvol
                        --volume-ctrl fixed
                        --initial-volume 100 \
                    # replay gain
                        --enable-volume-normalisation
                        --normalisation-pregain 0
                        --normalisation-method basic
                    --format F32 \
                    --name pre.di.c \
            > /dev/null
    ;;
    stop)
        killall librespot
    ;;
    *)
        echo
        echo "usage: librespot <start|stop>"
        echo
    ;;
esac

exit
