#!/usr/bin/env python3

""" 
    Loads the pulseaudio sink, in order to
    pulseaudio apps to sound through by JACK.

    use:    pulseaudio-jack-sink  start | stop
"""

import sys
from subprocess import Popen

def start():
    tmp = "pactl load-module module-jack-sink channels=2 client_name=pulse_sink connect=False"
    Popen(tmp.split())
    tmp = "pacmd set-default-sink jack_out"
    Popen(tmp.split())

def stop():
    tmp = "pactl unload-module module-jack-sink"
    Popen(tmp.split())

if sys.argv[1:]:
    try:
        option = {
            'start' : start,
            'stop'  : stop
            }[ sys.argv[1] ]()
    except:
        print('(pulseaudio-jack-sink) bad option')
else:
    print(__doc__)
