#!/bin/bash

echo "bass 0"             | nc -N localhost 9999
echo "treble 0"           | nc -N localhost 9999
echo "loudness_track off" | nc -N localhost 9999
echo "drc none"           | nc -N localhost 9999
