#!/bin/bash

echo "control bass 0"             | nc -N localhost 9999
echo "control treble 0"           | nc -N localhost 9999
echo "control loudness_track off" | nc -N localhost 9999
echo "control drc none"           | nc -N localhost 9999

